 version: 0.2


  env:
    variables:
      AWS_DEFAULT_REGION: ap-south-1
      IMAGE_REPO_NAME: brain-app IMAGE_TAG: latest
 phases:
 pre_build:
 commands:
  – echo Logging in to Amazon ECR...
  - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 190460274475.dkr.ecr.ap-south-1.amazonaws.com/brain-app
  build:
  commands:
   - echo Build started on 'date'
   - echo Building the Docker image.....
   - docker build -t $IMAGE_REPO_NAME: $IMAGE_TAG .
   - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG 190460274475.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME: $IMAGE_TAG
 post_build: 
  commands:
 - echo Build completed on 'date'
 - echo Pushing Docker image...
 - docker push 190460274475.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME: $IMAGE_TAG
 - echo Writing image definitions file...
 - printf '[{"name":"brain-app-container","imageUri":"%s"}]' 190460274475.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME: $IMAGE_TAG > i magedefinitions.json

artifacts:
files:
 - imagedefinitions.json
 - deployment.yaml
 - service.yaml
