AWSTemplateFormatVersion: '2010-09-09'
Description: Grant CodeBuild access to brain-cluster

Resources:

  CodeBuildAccessEntry:
    Type: AWS::EKS::AccessEntry
    Properties:
      ClusterName: brain-cluster
      PrincipalArn: arn:aws:iam::281089586720:role/service-role/codebuild-brain-eks-codebuild-service-role
      Type: STANDARD

  CodeBuildAccessPolicyAssociation:
    Type: AWS::EKS::AccessPolicyAssociation
    Properties:
      ClusterName: brain-cluster
      PrincipalArn: arn:aws:iam::281089586720:role/service-role/codebuild-brain-eks-codebuild-service-role
      PolicyArn: arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy
      AccessScope:
        Type: cluster

