apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-react-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-react-app
  template:
    metadata:
      labels:
        app: brain-react-app
    spec:
      containers:
      - name: brain-react-app
        image: 281089586720.dkr.ecr.ap-south-1.amazonaws.com/brain-react-app:latest
        ports:
        - containerPort: 3000
          resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
